exclude: typings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
      - id: pyright

  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.37
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: generate-changelog
        name: Generate Changelog
        # Use uv to run the command
        entry: bash -c 'echo "Generating changelog..." && uv pip install git-changelog && uv run gitchangelog > CHANGELOG.md && git add CHANGELOG.md || echo "Failed to generate changelog"'
        language: system
        pass_filenames: false
        stages: [pre-push]

  - repo: local
    hooks:
      - id: generate-docs
        name: Generate Documentation
        entry: bash -c 'uv run python docs/generate_docs.py'
        language: python
        pass_filenames: false

